blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('post/<slug:slug>/', views.post_detail_view, name='post_detail'),
    path('category/<slug:slug>/', views.category_view, name='category'),
    path('subcategory/<slug:slug>/', views.subcategory_view, name='subcategory'),
    path('newsletter/', views.newsletter_view, name='newsletter')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published=True)


class Post(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='post_created', null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='post_modified', null=True)
    last_modified = models.DateTimeField(auto_now=True, null=True, blank=True)
    title = models.CharField(max_length=60)
    slug = models.SlugField(max_length=80, unique=True)
    subcategory = models.ForeignKey('Subcategory', on_delete=models.SET_NULL, null=True)
    description = models.TextField()
    preparation = models.TextField()
    source = models.CharField(max_length=120, null=True, blank=True)
    published = models.BooleanField(default=True)
    objects = models.Manager()
    published_posts = PublishedPostManager()

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def get_main_photo(self):
        try:
            main_photo = self.photos.all()[0]
        except IndexError:
            main_photo = ''
        return main_photo

    def get_secondary_photos(self):
        secondary_photos = self.photos.all()[1:]
        return secondary_photos

    def get_comments_count(self):
        comments = Comment.published_comments.filter(post=self)
        return comments.count()


class Ingredient(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='ingredients')
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.content


class Photo(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='photos')
    image = models.ImageField(upload_to='blog/')

    def __str__(self):
        return self.image.url


class Category(models.Model):
    name = models.CharField(max_length=40, unique=True)
    slug = models.SlugField(max_length=60, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})


class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories')
    name = models.CharField(max_length=40, unique=True)
    slug = models.SlugField(max_length=60, unique=True)

    class Meta:
        verbose_name_plural = 'Subcategories'

    def __str__(self):
        return self.category.name + ' -> ' + self.name

    def get_absolute_url(self):
        return reverse('blog:subcategory', kwargs={'slug': self.slug})


class NewsletterSubscriber(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email


class PublishedCommentsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(published=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    reply_to = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name='reply_comments', null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=50)
    content = models.TextField()
    email = models.EmailField()
    published = models.BooleanField(default=False)
    is_post_author = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to='blog/', default='blog/anonymous-user.png')
    objects = models.Manager()
    published_comments = PublishedCommentsManager()

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return self.content

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import NewsletterSubscriber


class NewsletterForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'email'}))

    def clean_email(self):
        cleaned_email = self.cleaned_data['email']
        if NewsletterSubscriber.objects.filter(email=cleaned_email).exists():
            raise ValidationError('Użytkownik o podanym adresie email już istnieje.')
        return cleaned_email


class CommentForm(forms.Form):
    reply_to = forms.CharField(widget=forms.HiddenInput, required=False)
    name = forms.CharField(label='Imię', max_length=50)
    content = forms.CharField(label='Komentarz', widget=forms.Textarea)
    email = forms.EmailField(label='Email')
    captcha = forms.CharField(label='Rozwiąż', widget=forms.NumberInput)
    valid_captcha = forms.CharField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs, prefix='comment-add', auto_id=True)

    def clean_name(self):
        cleaned_name = self.cleaned_data['name']
        if not cleaned_name.isalpha():
            raise ValidationError('Pole powinno zawierać wyłącznie litery alfabetu.')
        return cleaned_name

    def clean(self):
        cleaned_data = super().clean()
        cleaned_captcha = cleaned_data['captcha']
        cleaned_valid_captcha = cleaned_data['valid_captcha']
        if not cleaned_captcha == cleaned_valid_captcha:
            self.add_error('captcha', ValidationError('Niepoprawny wynik CAPTCHA. Spróbuj jeszcze raz.'))
        return cleaned_data

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from .models import Post, Category, Subcategory, Comment
from .forms import CommentForm
from .utils import paginate

import random


def index_view(request):
    posts = Post.published_posts.all()
    paginator_context = paginate(request, posts)
    context = {
        **paginator_context
    }
    return render(request, 'blog/index_view.html', context)


def category_view(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = Post.published_posts.filter(subcategory__category__slug=slug)
    paginator_context = paginate(request, posts)
    context = {
        'category': category,
        **paginator_context
    }
    return render(request, 'blog/category_view.html', context)


def subcategory_view(request, slug):
    subcategory = get_object_or_404(Subcategory, slug=slug)
    posts = Post.published_posts.filter(subcategory__slug=slug)
    paginator_context = paginate(request, posts)
    context = {
        'subcategory': subcategory,
        **paginator_context
    }
    return render(request, 'blog/subcategory_view.html', context)


def post_detail_view(request, slug):
    post = get_object_or_404(Post, slug=slug)
    ingredients = post.ingredients.all()
    photos = post.get_secondary_photos()
    similar_posts = Post.published_posts.filter(subcategory=post.subcategory).exclude(pk=post.pk)
    similar_posts_len = len(similar_posts) if len(similar_posts) <= 4 else 4
    similar_posts = random.sample(list(similar_posts), k=similar_posts_len)

    previous_post = Post.published_posts.filter(created_on__lt=post.created_on).first()
    next_post = Post.published_posts.filter(created_on__gt=post.created_on).last()

    comments = Comment.published_comments.filter(post=post, reply_to=None).order_by('-created_on')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = Comment(
                post=post,
                name=form.cleaned_data['name'],
                content=form.cleaned_data['content'],
                email=form.cleaned_data['email']
            )
            if request.user == post.created_by:
                new_comment.is_post_author = True
                new_comment.published = True
                new_comment.avatar = 'blog/author-user.png'
            try:
                reply_to_pk = int(form.cleaned_data['reply_to'])
                if reply_to_pk not in [comment.pk for comment in comments]:
                    new_comment.reply_to = None
                else:
                    reply_comment = Comment.objects.get(pk=reply_to_pk)
                    new_comment.reply_to = reply_comment
            except (TypeError, ValueError, Comment.DoesNotExist):
                new_comment.reply_to = None
            new_comment.save()
            messages.success(request, 'Twój komentarz został dodany i czeka na akceptację.')
            return redirect(post.get_absolute_url() + '#comment-add')
    else:
        form = CommentForm()
    captcha1 = random.randint(11, 29)
    captcha2 = random.randint(1, 9)
    valid_captcha = captcha1 - captcha2
    context = {
        'post': post,
        'ingredients': ingredients,
        'photos': photos,
        'similar_posts': similar_posts,
        'previous_post': previous_post,
        'next_post': next_post,
        'comments': comments,
        'form': form,
        'captcha1': captcha1,
        'captcha2': captcha2,
        'valid_captcha': valid_captcha
    }
    return render(request, 'blog/post_detail_view.html', context)


def newsletter_view(request):
    return render(request, 'blog/newsletter_view.html', {})

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %} | {{ request.get_host }}</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
  <script src="{% static 'blog/commentAdd.js' %}"></script>
  <script src="https://kit.fontawesome.com/2ffe2eafe6.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&display=swap" rel="stylesheet">
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v15.0" nonce="AJU8EHi3"></script>
</head>
<body>
  <header>
    <div class="site-logo">
      <div class="site-title">
        <h1><a href="{% url 'blog:index' %}">Culinary blog</a></h1>
      </div>
      <div class="site-description">sprawdzone przepisy kulinarne</div>
    </div>
  </header>

  {% include 'blog/nav.html' %}

  <main>
    <div class="site-content">
      {% block content %}
      {% endblock %}
    </div>

    {% include 'blog/features.html' %}
  </main>

  <footer>
    <p><a href="https://www.github.com/felidevz" target="_blank">@felidev</a></p>
  </footer>
</body>
</html>

blog/templates/blog/category_view.html
{% extends 'blog/base.html' %}

{% block title %}{{ category.name|capfirst }}{% endblock %}

{% block content %}
  {% include 'blog/posts.html' %}

  <div class="pagination">
    <ul class="page-numbers">
      {% if page_obj.has_previous %}
        <li><a href="{{ category.get_absolute_url }}?page={{ page_obj.previous_page_number }}">&laquo; Poprzednia strona</a></li>
      {% endif %}

      {% for page_nr in page_range %}
        {% if page_nr == page_obj.paginator.ELLIPSIS %}
          <li><a class="inactive">{{ page_nr }}</a></li>
        {% elif page_nr == page_obj.number %}
          <li><a class="current">{{ page_nr }}</a></li>
        {% else %}
          <li><a href="{{ category.get_absolute_url }}?page={{ page_nr }}">{{ page_nr }}</a></li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li><a href="{{ category.get_absolute_url }}?page={{ page_obj.next_page_number }}">Następna strona &raquo;</a></li>
      {% endif %}
    </ul>
  </div>
{% endblock %}

blog/templates/blog/features.html
<div class="features">
  <div class="facebook">
    <div class="features-title">
      <p>Facebook</p>
    </div>
    <div class="fb-page" data-href="https://www.facebook.com/facebook" data-tabs="" data-width="500" data-height="" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-lazy="true"><blockquote cite="https://www.facebook.com/facebook" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/facebook">Facebook</a></blockquote></div>
  </div>

  <div class="socials">
    <div class="features-title">
      <p>Socials</p>
    </div>
    <div class="icons">
      <div class="social">
        <a href="https://www.twitter.com/" target="_blank">
          <i class="fa-brands fa-twitter"></i>
          <p>Twitter</p>
        </a>
      </div>
      <div class="social">
        <a href="https://www.instagram.com/" target="_blank">
          <i class="fa-brands fa-instagram"></i>
          <p>Instagram</p>
        </a>
      </div>
      <div class="social">
        <a href="https://www.facebook.com/" target="_blank">
          <i class="fa-brands fa-facebook"></i>
          <p>Facebook</p>
        </a>
      </div>
      <div class="social">
        <a href="https://www.pinterest.com/" target="_blank">
          <i class="fa-brands fa-pinterest"></i>
          <p>Pinterest</p>
        </a>
      </div>
      <div class="social">
        <a href="https://www.tiktok.com/" target="_blank">
          <i class="fa-brands fa-tiktok"></i>
          <p>Tiktok</p>
        </a>
      </div>
      <div class="social">
        <a href="https://www.youtube.com/" target="_blank">
          <i class="fa-brands fa-youtube"></i>
          <p>Youtube</p>
        </a>
      </div>
    </div>
  </div>

  <div class="newsletter">
    <div class="features-title">
      <p>Newsletter</p>
    </div>
    <p class="newsletter-text">Zapisz się do newslettera, aby otrzymywać powiadomienia o nowych przepisach.</p>
    <form action="{% url 'blog:newsletter' %}" method="POST">
      {% csrf_token %}
      <input type="email" name="email" placeholder="email" required>
      <button>Subskrybuj</button>
    </form>
  </div>
</div>

blog/templates/blog/index_view.html
{% extends 'blog/base.html' %}

{% block title %}
  <title>Culinary blog | {{ request.get_host }}</title>
{% endblock %}

{% block content %}
  {% for post in page_obj %}
    <div class="content-row {% cycle 'odd' 'even' %}">
      <div class="content-image" style="background-image: url('{{ post.photo.first.image.url }}');">
        <a href="{% url 'blog:post_detail' post.slug %}" title="{{ post.title }}">
          <div class="content-date {% cycle 'left-date' 'right-date' %}">
            <p>{{ post.created_on|date:'d E Y' }}</p>
          </div>
        </a>
      </div>
      <div class="content-description">
        <div class="content-category">
          <span><a href="{% url 'blog:category' post.subcategory.category.slug %}">{{ post.subcategory.category }}</a></span>
        </div>
        <h2><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h2>
        <p>{{ post.description|truncatechars:300|capfirst }}</p>
        <a href="{% url 'blog:post_detail' post.slug %}" class="content-read">Czytaj dalej</a>
        <a href="{% url 'blog:post_detail' post.slug %}" class="content-comments"><i class="fa-solid fa-comments"></i>Komentarzy: 2</a>
      </div>
    </div>
  {% endfor %}


    <div class="pagination">
      <ul class="page-numbers">
        {% if page_obj.has_previous %}
          <li><a href="{% url 'blog:index' %}?page={{ page_obj.previous_page_number }}">&laquo; Poprzednia strona</a></li>
        {% endif %}

        {% for page_nr in page_range %}
          {% if page_nr == page_obj.paginator.ELLIPSIS %}
            <li><a class="inactive">{{ page_nr }}</a></li>
          {% elif page_nr == page_obj.number %}
            <li><a class="current">{{ page_nr }}</a></li>
          {% else %}
            <li><a href="{% url 'blog:index' %}?page={{ page_nr }}">{{ page_nr }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li><a href="{% url 'blog:index' %}?page={{ page_obj.next_page_number }}">Następna strona &raquo;</a></li>
        {% endif %}
      </ul>
    </div>
{% endblock %}

blog/templates/blog/nav.html
<nav>
  <div class="site-menu">
    <ul class="site-nav">
      {% for category in categories %}
        <li class="menu-item">
          <a href="{% url 'blog:category' category.slug %}">{{ category.name }}</a>

          <div class="dropdown-menu">
            <ul class="dropdown-nav">
              {% for subcategory in category.subcategory.all %}
                <li class="dropdown-item"><a href="{% url 'blog:subcategory' subcategory.slug %}">{{ subcategory.name }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </li>
      {% endfor %}
    </ul>
  </div>
</nav>

blog/templates/blog/newsletter_view.html
{% extends 'blog/base.html' %}

{% block title %}
<title>Newsletter | {{ request.get_host }}</title>
{% endblock %}

{% block content %}
  <div class="newsletter-detail">

    <h2 class="newsletter-confirmation">
      {% if bad_request %}
        {{ bad_request }}
      {% elif error %}
        {{ error }}
      {% elif subscriber %}
        {{ subscriber }}
      {% else %}
        Thank you for subscribing
      {% endif %}
    </h2>

    <p class="newsletter-info">
      {% if bad_request %}
        You tried to access this page directly.<br>
        Enter your email address in the newsletter form instead.
      {% elif error %}
        Sorry, you entered an incorrect email address.<br>
        Please correct it and try again.
      {% elif subscriber %}
        A user with the given email address already exists and receives notifications about new recipes.
      {% else %}
        From now you will receive notifications about new recipes on the website.
      {% endif %}
    </p>
  </div>
{% endblock %}

blog/templates/blog/post_detail_view.html
{% extends 'blog/base.html' %}

{% block title %}
  <title>{{ post.title|capfirst }} | {{ request.get_host }}</title>
{% endblock %}

{% block content %}
  <div class="content-category post-category">
    <span>{{ post.created_on|date:'d E Y' }} / <a href="{% url 'blog:category' post.subcategory.category.slug %}">{{ post.subcategory.category }}</a></span>
  </div>
  <h2 class="post-title">{{ post.title }}</h2>
  <p class="post-description">{{ post.description }}</p>
  <div class="post-image" title="{{ post.title }}" style="background-image: url('{{ post.photo.first.image.url }}');"></div>

  <div class="post-content">
    <p class="post-section-title">Składniki:</p>
    <ul>
      {% for ingredient in post.ingredients.all %}
        <li>{{ ingredient }}</li>
      {% endfor %}
    </ul>
    <p class="post-section-title">Przygotowanie:</p>
    <p class="post-preparation">{{ post.preparation|capfirst }}</p>
    <p class="post-greetings">Smacznego!</p>
  </div>

  <div class="post-gallery">
    {% for photo in photos %}
      <div style="background-image: url('{{ photo.image.url }}');"></div>
    {% endfor %}
  </div>

  <p class="recipe-source">Źródło: <a href="google.pl">google.pl</a></p>

  {% if more_posts %}
    <div class="more-posts">
      <p>Sprawdź także:</p>
      <div class="posts">
        {% for post in more_posts %}
          <div class="post">
            <a href="{% url 'blog:post_detail' post.slug %}">
              <img src="{{ post.photo.first.image.url }}">
              <p>{{ post.title }}</p>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  {% endif %}

  <div class="previous-next-posts">
    {% if previous_post %}
      <a href="{% url 'blog:post_detail' previous_post.slug %}" class="previous-post">
        <p>&laquo; Poprzedni wpis</p>
        <p class="previous-post-title">{{ previous_post.title }}</p>
      </a>
    {% endif %}

    {% if next_post %}
      <a href="{% url 'blog:post_detail' next_post.slug %}" class="next-post">
        <p>Następny wpis &raquo;</p>
        <p class="next-post-title">{{ next_post.title }}</p>
      </a>
    {% endif %}
  </div>

  <div class="comments-section">
    <p class="comments-counter">Komentarzy: {{ comments_count }}</p>

    {% for comment in comments %}
      <div class="single-comment">
        <div class="comment-header">
          <img src="{{ comment.avatar.url }}">
          <div class="comment-info">
            <p class="comment-author">{{ comment.name }} {% if comment.is_post_author %}<span class="comment-post-author">Autor</span>{% endif %}</p>
            <p class="comment-date">{{ comment.created_on|date:'d M Y' }} / {{ comment.created_on|time:'H:i' }}</p>
          </div>
        </div>

        <p class="comment-content">{{ comment.content|capfirst }}</p>

        <p class="comment-reply"><a class="comment-reply-href" onclick="hideShowCommentAdd('{{ comment.pk }}')"><i class="fa-solid fa-reply"></i> Odpowiedz</a></p>

        {% for reply in comment.reply_comments.all %}
          <div class="single-comment-reply">
            <div class="comment-header">
              <img src="{{ reply.avatar.url }}">
              <div class="comment-info">
                <p class="comment-author">{{ reply.name }} {% if reply.is_post_author %}<span class="comment-post-author">Autor</span>{% endif %}</p>
                <p class="comment-date">{{ reply.created_on|date:'d M Y' }} / {{ reply.created_on|time:'H:i' }}</p>
              </div>
            </div>

            <p class="comment-content-reply">{{ reply.content|capfirst }}</p>
          </div>
        {% endfor %}

        <div id="comment-add-reply-{{ comment.pk }}" class="comment-add comment-add-reply">
          <p class="comment-add-title">Odpowiedz użytkownikowi {{ comment.name }} <a class="reply-cancel" onclick="hideShowCommentAdd('{{ comment.pk }}')"><i class="fa-sharp fa-solid fa-comment-slash"></i> Anuluj pisanie odpowiedzi</a></p>
          <p class="comment-add-description">Twój adres email nie zostanie opublikowany.</p>

          <form action="" method="POST">
            {% csrf_token %}

            <input type="hidden" name="comment-add-reply_to" value="{{ comment.pk }}">

            {{ form.non_field_errors }}

            {{ form.name.label_tag }}
            {{ form.name.errors }}
            {{ form.name }}

            {{ form.content.label_tag }}
            {{ form.content.errors }}
            {{ form.content }}

            {{ form.email.label_tag }}
            {{ form.email.errors }}
            {{ form.email }}

            {{ form.captcha.label_tag }}
            {{ form.captcha.errors }}
            <p>
              <span class="comment-add-captcha">{{ captcha1 }} - {{ captcha2 }} = </span>
              {{ form.captcha }}
            </p>
            <input type="hidden" name="comment-add-valid_captcha" value="{{ valid_captcha }}">

            <button type="submit">Opublikuj</button>
          </form>
        </div>

        <hr>
      </div>
    {% endfor %}


    <div id="comment-add" class="comment-add">
      <p class="comment-add-title">Dodaj komentarz</p>
      <p class="comment-add-description">Twój adres email nie zostanie opublikowany.</p>

      <form action="" method="POST">
        {% csrf_token %}

        <input type="hidden" name="comment-add-reply_to" value="">

        {{ form.non_field_errors }}

        {{ form.name.label_tag }}
        {{ form.name.errors }}
        {{ form.name }}

        {{ form.content.label_tag }}
        {{ form.content.errors }}
        {{ form.content }}

        {{ form.email.label_tag }}
        {{ form.email.errors }}
        {{ form.email }}

        {{ form.captcha.label_tag }}
        {{ form.captcha.errors }}
        <p>
          <span class="comment-add-captcha">{{ captcha1 }} - {{ captcha2 }} = </span>
          {{ form.captcha }}
        </p>
        <input type="hidden" name="comment-add-valid_captcha" value="{{ valid_captcha }}">

        <button type="submit">Opublikuj</button>
      </form>
    </div>
  </div>
{% endblock %}

blog/templates/blog/subcategory_view.html
{% extends 'blog/base.html' %}

{% block title %}
<title>{{ subcategory.name|capfirst }} | {{ request.get_host }}</title>
{% endblock %}

{% block content %}
  {% for post in page_obj %}
    <div class="content-row {% cycle 'odd' 'even' %}">
      <div class="content-image" style="background-image: url('{{ post.photo.first.image.url }}');">
        <a href="{% url 'blog:post_detail' post.slug %}" title="{{ post.title }}">
          <div class="content-date {% cycle 'left-date' 'right-date' %}">
            <p>{{ post.created_on|date:'d E Y' }}</p>
          </div>
        </a>
      </div>
      <div class="content-description">
        <div class="content-category">
          <span><a href="{% url 'blog:category' post.subcategory.category.slug %}">{{ post.subcategory.category }}</a></span>
        </div>
        <h2><a href="{% url 'blog:post_detail' post.slug %}">{{ post.title }}</a></h2>
        <p>{{ post.description|truncatechars:300|capfirst }}</p>
        <a href="{% url 'blog:post_detail' post.slug %}" class="content-read">Czytaj dalej</a>
        <a href="{% url 'blog:post_detail' post.slug %}" class="content-comments"><i class="fa-solid fa-comments"></i>Komentarzy: 2</a>
      </div>
    </div>
  {% endfor %}


    <div class="pagination">
      <ul class="page-numbers">
        {% if page_obj.has_previous %}
          <li><a href="{% url 'blog:subcategory' subcategory.slug %}?page={{ page_obj.previous_page_number }}">&laquo; Poprzednia strona</a></li>
        {% endif %}

        {% for page_nr in page_range %}
          {% if page_nr == page_obj.paginator.ELLIPSIS %}
            <li><a class="inactive">{{ page_nr }}</a></li>
          {% elif page_nr == page_obj.number %}
            <li><a class="current">{{ page_nr }}</a></li>
          {% else %}
            <li><a href="{% url 'blog:category' subcategory.slug %}?page={{ page_nr }}">{{ page_nr }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li><a href="{% url 'blog:category' subcategory.slug %}?page={{ page_obj.next_page_number }}">Następna strona &raquo;</a></li>
        {% endif %}
      </ul>
    </div>
{% endblock %}